### ISSUE TITLE
multiple panel selector

### ISSUE THREAD

**Issue by develhopper** [EMH-Mark-I/xfce4_panelbar_theming#2]
Hi, what about when we have multiple panel and we want apply style on one of them?
is there any specific selector to select a specific panel?

**Comment by EMH-Mark-I** [comment]
I don't believe there is any way from a theme perspective to specifically style individual panel bars among a group since they're not enumerated by the toolkit (e.g. `.panel-1`, `.panel-2`, `.panel-3`.)

The panel bar has a single selector ID `#XfcePanelWindow` and an XFCE specific class name, `.xfce4-panel`.

There is also the selector class `.panel` for compatibility with other GTK themes that might not specifically target XFCE and `.background`. Additionally, `.horizontal` and `.vertical` which can be used when the panel bar is made vertical or horizontal.
